### ISSUE TITLE
Missing POM file for mqtt-websocket-java

### ISSUE THREAD

**Issue by vineetdgithub** [inventit/mqtt-websocket-java#5]
I was following installation instructions when I encountered following error.

Downloading: https://repo.maven.apache.org/maven2/io/inventit/dev/mqtt-websocket-java/1.0.1/mqtt-websocket-java-1.0.1.pom
[WARNING] The POM for io.inventit.dev:mqtt-websocket-java:jar:1.0.1 is missing, no dependency information available

Is this moved some place else?

**Comment by dbaba** [comment]
I'd say you didn't install the jar file with `mvn install` command since the jar file wasn't on the maven central repository.
Please follow [this installation instruction](https://github.com/inventit/mqtt-websocket-java/releases/tag/1.0.1).


BTW, I noticed that the README.md didn't contain how to install and so I've just appended it. Thanks for the feedback.
